package com.ken.base.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ken.base.model.ExpressInfo;

import com.ken.base.greendao.ExpressInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig expressInfoDaoConfig;

    private final ExpressInfoDao expressInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        expressInfoDaoConfig = daoConfigMap.get(ExpressInfoDao.class).clone();
        expressInfoDaoConfig.initIdentityScope(type);

        expressInfoDao = new ExpressInfoDao(expressInfoDaoConfig, this);

        registerDao(ExpressInfo.class, expressInfoDao);
    }
    
    public void clear() {
        expressInfoDaoConfig.clearIdentityScope();
    }

    public ExpressInfoDao getExpressInfoDao() {
        return expressInfoDao;
    }

}
