package com.ken.base.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ken.base.model.ExpressListConvert;
import java.util.List;

import com.ken.base.model.ExpressInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXPRESS_INFO".
*/
public class ExpressInfoDao extends AbstractDao<ExpressInfo, Long> {

    public static final String TABLENAME = "EXPRESS_INFO";

    /**
     * Properties of entity ExpressInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property No = new Property(1, String.class, "no", false, "NO");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Logo = new Property(3, String.class, "logo", false, "LOGO");
        public final static Property List = new Property(4, String.class, "list", false, "LIST");
    }

    private final ExpressListConvert listConverter = new ExpressListConvert();

    public ExpressInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ExpressInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXPRESS_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NO\" TEXT UNIQUE ," + // 1: no
                "\"NAME\" TEXT," + // 2: name
                "\"LOGO\" TEXT," + // 3: logo
                "\"LIST\" TEXT);"); // 4: list
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXPRESS_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ExpressInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String no = entity.getNo();
        if (no != null) {
            stmt.bindString(2, no);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String logo = entity.getLogo();
        if (logo != null) {
            stmt.bindString(4, logo);
        }
 
        List list = entity.getList();
        if (list != null) {
            stmt.bindString(5, listConverter.convertToDatabaseValue(list));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ExpressInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String no = entity.getNo();
        if (no != null) {
            stmt.bindString(2, no);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String logo = entity.getLogo();
        if (logo != null) {
            stmt.bindString(4, logo);
        }
 
        List list = entity.getList();
        if (list != null) {
            stmt.bindString(5, listConverter.convertToDatabaseValue(list));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ExpressInfo readEntity(Cursor cursor, int offset) {
        ExpressInfo entity = new ExpressInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // no
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // logo
            cursor.isNull(offset + 4) ? null : listConverter.convertToEntityProperty(cursor.getString(offset + 4)) // list
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ExpressInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLogo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setList(cursor.isNull(offset + 4) ? null : listConverter.convertToEntityProperty(cursor.getString(offset + 4)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ExpressInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ExpressInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ExpressInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
